# hystrix.command.default.execution.timeout.enabled: false
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 80000
spring:
  application:
    name: cloud-client-config
  profiles:
    active: dev

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

logging:
  config: classpath:logback.xml